/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Cat
 */
export interface Cat {
    /**
     * The age of the Cat
     * @type {number}
     * @memberof Cat
     */
    'age': number;
    /**
     * The breed of the Cat
     * @type {string}
     * @memberof Cat
     */
    'breed': string;
}

